import type { MatchRecord } from "./match-types";

export function createDemoMatches(): MatchRecord[] {
  return [
    {
      id: "demo-1",
      matchNumber: 1,
      teamAName: "Chennai Super Kings",
      teamBName: "Royal Challengers Bengaluru",
      teamAShort: "CSK",
      teamBShort: "RCB",
      startAt: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
      lockAt: new Date(Date.now() + 115 * 60 * 1000).toISOString(),
      status: "upcoming",
      winner: null,
      isEditableBeforeLock: true,
      createdBy: "demo",
    },
    {
      id: "demo-2",
      matchNumber: 2,
      teamAName: "Mumbai Indians",
      teamBName: "Gujarat Titans",
      teamAShort: "MI",
      teamBShort: "GT",
      startAt: new Date(Date.now() + 26 * 60 * 60 * 1000).toISOString(),
      lockAt: new Date(Date.now() + 25 * 60 * 60 * 1000 + 55 * 60 * 1000).toISOString(),
      status: "upcoming",
      winner: null,
      isEditableBeforeLock: true,
      createdBy: "demo",
    },
    {
      id: "demo-3",
      matchNumber: 3,
      teamAName: "Kolkata Knight Riders",
      teamBName: "Sunrisers Hyderabad",
      teamAShort: "KKR",
      teamBShort: "SRH",
      startAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
      lockAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
      status: "locked",
      winner: null,
      isEditableBeforeLock: false,
      createdBy: "demo",
    },
    {
      id: "demo-4",
      matchNumber: 4,
      teamAName: "Rajasthan Royals",
      teamBName: "Lucknow Super Giants",
      teamAShort: "RR",
      teamBShort: "LSG",
      startAt: new Date(Date.now() - 28 * 60 * 60 * 1000).toISOString(),
      lockAt: new Date(Date.now() - 28 * 60 * 60 * 1000 - 5 * 60 * 1000).toISOString(),
      status: "settled",
      winner: "teamA",
      isEditableBeforeLock: false,
      createdBy: "demo",
      settledAt: new Date(Date.now() - 25 * 60 * 60 * 1000).toISOString(),
      settledBy: "demo-admin",
    },
  ];
}

